### PR TITLE
OKTA-709693: make userschemaattribute minlength maxlength nullable

### LINKED ISSUE #702: UserSchemaAttributes minLength and maxLength are non-nullable and cause array schema attribute creation to fail.
### Describe the bug?

SMH.  At what point does Okta realize that we are paying customers, and it is just embarrassing how many bugs there are that are not being fixed in this SDK?

In the UserSchemaAttribute class, the properties minLength and maxLength are non-nullable.  When creating an array type attribute, minLength and maxLength properties are being sent with a value of 0.  This causes `ISchemaApiAsync.UpdateApplicationUserProfileAsync()` to fail with the error message `Api validation failed: The type: array is not a string type and supported with minLength and maxLength.`

### What is expected to happen?

minLength and maxLength properties should not be sent (null)

### What is the actual behavior?

minLength and maxLength properties are sent with a zero value.

### Reproduction Steps?

Get an existing UserSchema and add an array attribute to it

```
Dictionary<string, UserSchemaAttribute> customAttributes = userSchema.Definitions.Custom.Properties ??
                                                                   throw new InvalidOperationException(
                                                                       "Custom attributes are null.");
 var userSchemaAttribute = new UserSchemaAttribute
        {
            Type = UserSchemaAttributeType.Array,
            Title = "someName",
            Required = false,
            Scope = UserSchemaAttributeScope.NONE,
            ExternalName = "someExternalName",
            Items = new UserSchemaAttributeItems { Type = "string" }
        };
customAttributes.Add(attributeName, userSchemaAttribute);
schemaApiAsync.UpdateApplicationUserProfileAsync(idpId,userSchema)
```

### Additional Information?

_No response_

### .NET Version

8.0.200

### SDK Version

8.0.200

### OS version

Darwin MacBook-Pro-3.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64

### LINKED ISSUE #712: 500 Error Due to UserSchemaAttribute and UserSchemaAttribute items sending null values
### Describe the bug?

Both UserSchemaAttribute and UserSchemaAttributeItems apply annotations to property members to send default values, which is null for non intrinsics.  A 500 error results when calling the schema API due to the null values being present.

### What is expected to happen?

Null properties should not be sent in API calls like:

```bash
curl --location 'https://sso.precisely.services/api/v1/meta/schemas/apps/theSchemaId/default' \
--header 'Authorization: SSWS theToken' \
--header 'Content-Type: application/json' \
--header 'Cookie: JSESSIONID=theSessionId' \
--data '{
    "definitions": {
        "custom": {
            "id": "#custom",
            "properties": {
                "firstName": {
                    "scope": "NONE",
                    "type": "string",
                    "externalName": "firstName",
                    "maxLength": 50,
                    "minLength": 0,
                    "required": true,
                    "title": "firstName"
                },
                "lastName": {
                    "scope": "NONE",
                    "type": "string",
                    "externalName": "lastName",
                    "maxLength": 50,
                    "minLength": 0,
                    "required": true,
                    "title": "lastName"
                },
                "email": {
                    "scope": "NONE",
                    "type": "string",
                    "externalName": "email",
                    "maxLength": 100,
                    "minLength": 0,
                    "required": true,
                    "title": "email"
                },
                "mobilePhone": {
                    "scope": "NONE",
                    "type": "string",
                    "externalName": "mobilePhone",
                    "maxLength": 100,
                    "minLength": 0,
                    "required": false,
                    "title": "Mobile Phone"
                },
                "federatedGroups": {
                    "scope": "NONE",
                    "type": "array",
                    "union": "DISABLE",
                    "externalName": "federatedGroups",
                    "items": {
                        "type": "string"
                    },
                    "required": false,
                    "title": "federatedGroups"
                }
            },
            "required": [
                "firstName",
                "lastName",
                "email"
            ],
            "type": "object"
        }
    },
    "properties": {
        "profile": {
            "allOf": [
                null,
                null
            ]
        }
    },
    "title": "identity.precisely.services-00u208epblm6akcYu0h8 User"
}'
```

### What is the actual behavior?

Null values are being sent
```bash
curl --location 'https://sso.precisely.services/api/v1/meta/schemas/apps/theSchemaId/default' \
--header 'Authorization: SSWS theToken' \
--header 'Content-Type: application/json' \
--header 'Cookie: JSESSIONID=theSessionId' \
--data '{
    "definitions": {
        "custom": {
            "id": "#custom",
            "properties": {
                "firstName": {
                    "scope": "NONE",
                    "type": "string",
                    "union": null,
                    "description": null,
                    "enum": null,
                    "externalName": "firstName",
                    "externalNamespace": null,
                    "items": null,
                    "master": null,
                    "maxLength": 50,
                    "minLength": 0,
                    "mutability": null,
                    "oneOf": null,
                    "pattern": null,
                    "permissions": null,
                    "required": true,
                    "title": "firstName",
                    "unique": null
                },
                "lastName": {
                    "scope": "NONE",
                    "type": "string",
                    "union": null,
                    "description": null,
                    "enum": null,
                    "externalName": "lastName",
                    "externalNamespace": null,
                    "items": null,
                    "master": null,
                    "maxLength": 50,
                    "minLength": 0,
                    "mutability": null,
                    "oneOf": null,
                    "pattern": null,
                    "permissions": null,
                    "required": true,
                    "title": "lastName",
                    "unique": null
                },
                "email": {
                    "scope": "NONE",
                    "type": "string",
                    "union": null,
                    "description": null,
                    "enum": null,
                    "externalName": "email",
                    "externalNamespace": null,
                    "items": null,
                    "master": null,
                    "maxLength": 100,
                    "minLength": 0,
                    "mutability": null,
                    "oneOf": null,
                    "pattern": null,
                    "permissions": null,
                    "required": true,
                    "title": "email",
                    "unique": null
                },
                "mobilePhone": {
                    "scope": "NONE",
                    "type": "string",
                    "union": null,
                    "description": null,
                    "enum": null,
                    "externalName": "mobilePhone",
                    "externalNamespace": null,
                    "items": null,
                    "master": null,
                    "maxLength": 100,
                    "minLength": 0,
                    "mutability": null,
                    "oneOf": null,
                    "pattern": null,
                    "permissions": null,
                    "required": false,
                    "title": "Mobile Phone",
                    "unique": null
                },
                "federatedGroups": {
                    "scope": "NONE",
                    "type": "array",
                    "union": "DISABLE",
                    "externalName": "federatedGroups",
                    "items": {
                        "enum": null,
                        "oneOf": null,
                        "type": "string"
                    },
                    "required": false,
                    "title": "federatedGroups"
                }
            },
            "required": [
                "firstName",
                "lastName",
                "email"
            ],
            "type": "object"
        }
    },
    "properties": {
        "profile": {
            "allOf": [
                null,
                null
            ]
        }
    },
    "title": "IdpTitle User"
}'
```

### Reproduction Steps?

See https://github.com/okta/okta-sdk-dotnet/issues/702 for same reproduction steps.

### Additional Information?

See https://github.com/okta/okta-sdk-dotnet/issues/702 for workaround code.

### .NET Version

8.0.203

### SDK Version

7.0.6

### OS version

_No response_

### PR DESCRIPTION
**Pull request by bryanapellanes-okta**
- Make UserSchemaAttribute.MinLength nullable
- Make UserSchemaAttribute.MaxLength nullable

Fixes #702

### CODE REVIEW

**Comment by rcollette** [comment]
@bryanapellanes-okta - I'm not seeing code that would resolve #712 ?

**Comment by bryanapellanes-okta** [comment]
> @bryanapellanes-okta - I'm not seeing code that would resolve #712 ?

@rcollette Thanks for your patience on this.  I apologize for the oversight, I am reviewing this further to address #712.

**Comment by bryanapellanes-okta** [comment]
@rcollette Upon closer inspection the solution to #712 requires additional consideration.  I've removed the "fixes" declaration for #712  from this PR.  I will investigate further to determine an appropriate fix for #712.

**Comment by laura-rodriguez** [comment]
LGTM, @bryanapellanes-okta please confirm the spec changes with the API team before merging.

**Review by laura-rodriguez — APPROVED** [review]

**Comment by bryanapellanes-okta** [comment]
> LGTM, @bryanapellanes-okta please confirm the spec changes with the API team before merging.

related spec change https://github.com/atko-eng/okta-oas3/pull/983

**Pull request merged**
