### PR TITLE
Fixed README to use correct OktaClientConfiguration Property

### PR DESCRIPTION
**Pull request by jusso-dev**
Updated README to use the new OktaClientConfiguration OktaDomain string Property

### CODE REVIEW

**Comment by nbarbettini** [comment]
Thanks @jusso-dev! I totally missed this.

**Comment by jusso-dev** [comment]
Not a problem, there's actually a lot more instances of this however throughout the code, ie. code comments, documentation etc, did you want me to pick up what I can find and change those as well?

**Comment by laura-rodriguez** [comment]
Thanks for your contribution @jusso-dev! I will merge your PR soon. Feel free to continue contributing ❤️

**Comment by nbarbettini** [comment]
@jusso-dev Any and all contributions are welcome!

**Comment by laura-rodriguez** [comment]
Merged via #285

**Pull request closed without merging**
