### PR TITLE
DO NOT MERGE: Disables SSL check for testing

### PR DESCRIPTION
**Pull request by vijetmahabaleshwar-okta**

### CODE REVIEW

**Comment by laura-rodriguez** [comment]
@vijetmahabaleshwar-okta validations are no longer part of the `DefaultRequestExecutor`, there is a pending [PR](https://github.com/okta/okta-sdk-dotnet/pull/262) where you can see these changes.
On the other hand, I know you are blocked by this. @nbarbettini now that we all agreed on how to implement this, would you like to prioritize this so we can unblock Vijet?

**Comment by vijetmahabaleshwar-okta** [comment]
Thanks @laura-rodriguez.
I wanted to check if the tests pass on bacon without the SSL check. 
In fact, it worked. Now, we have a test suite to run the .NET ITs on bacon! 🔥 

dotnet-sdk

**Comment by nbarbettini** [comment]
@laura-rodriguez I'll merge #262 this morning, and we can get 1.0.0 stable prepped for release. I don't want to hold up 1.0.0, but we can do this right afterwards to unblock Vijet.

**Comment by nbarbettini** [comment]
Closing this in favor of #265.

**Pull request closed without merging**
