### PR TITLE
Add support for errorCauses

### PR DESCRIPTION
**Pull request by nbarbettini**
Pulled in #182 from @ryannewington plus some internal refactoring to better support deserializing lists of objects properly.

### CODE REVIEW

**Comment by nbarbettini** [comment]
@ryannewington I took your PR one step further and actually exposed the `errorCauses` as a real list of objects. This revealed some areas of the internal deserialization code that needed to be updated.

What do you think of the `ErrorCauses` and `DetailedMessage` properties? It's pretty close to your PR but I made a few small changes.

**Comment by ryannewington** [comment]
@nbarbettini structuring the exception with those additional fields is good, an enhances the programmatic access to the data. However, it hides a lot of the information from standard logging libraries which are going to call ToString() on the exception. The real important information about the exception gets lost, unless you force consumers to catch these exceptions and handle them as special cases.

I suggest if you want to keep a simpler 'message' string, that we override ToString() to include all the relevant information about the error, so it's out-of-the-box compatible with existing logging strategies without having to write a custom renderer.

Even custom renderers are a pain in this SDK, because Async always returns AggregateExceptions that need to be unwrapped. So each place you have an exception, you need to check to see if its an AggregateException, unwrap it, check if its an OktaApiException, format a useful error message based on all the various properties. It's a lot of work for no real value.

For example, the previous API version logs this, and you have no idea what went wrong
```
Okta.Sdk.OktaApiException: Api validation failed
   at Okta.Sdk.Internal.DefaultDataStore.EnsureResponseSuccess(HttpResponse`1 response)
   at Okta.Sdk.Internal.DefaultDataStore.<PostAsync>d__19`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Okta.Sdk.OktaClient.<PostAsync>d__24`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Okta.Sdk.UsersClient.<CreateUserAsync>d__3.MoveNext()Okta.Sdk.OktaApiException: 400: Api validation failed: login
login: An object with this field already exists in the current organization
   at Okta.Sdk.Internal.DefaultDataStore.EnsureResponseSuccess(HttpResponse`1 response)
   at Okta.Sdk.Internal.DefaultDataStore.<PostAsync>d__19`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Okta.Sdk.OktaClient.<PostAsync>d__24`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Okta.Sdk.UsersClient.<CreateUserAsync>d__3.MoveNext()
```

With the original PR, we can actually see the reason for the failure
```
Okta.Sdk.OktaApiException: 400: Api validation failed: login
login: An object with this field already exists in the current organization
   at Okta.Sdk.Internal.DefaultDataStore.EnsureResponseSuccess(HttpResponse`1 response)
   at Okta.Sdk.Internal.DefaultDataStore.<PostAsync>d__19`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Okta.Sdk.OktaClient.<PostAsync>d__24`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Okta.Sdk.UsersClient.<CreateUserAsync>d__3.MoveNext()Okta.Sdk.OktaApiException: 400: Api validation failed: login
login: An object with this field already exists in the current organization
   at Okta.Sdk.Internal.DefaultDataStore.EnsureResponseSuccess(HttpResponse`1 response)
   at Okta.Sdk.Internal.DefaultDataStore.<PostAsync>d__19`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Okta.Sdk.OktaClient.<PostAsync>d__24`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Okta.Sdk.UsersClient.<CreateUserAsync>d__3.MoveNext()
```
In my use case, i'm writing a synchronization adapter for an identity management product, and need to float useful failure messages up to the user so they can see it in the UI
image

Personally, I don't think there is any value in having a message string that says only "Api validation failed". It maps nicely to the REST error object, but doesn't serve much purpose other than that. It's forcing the consumer to always do work to get to the 'real' error message.

I think as a minimum a custom ToString() method is needed, but I do think there is value in a meaningful and useful Message property that bubbles up nicely through the framework and doesn't require special handling.

**Comment by nbarbettini** [comment]
@ryannewington I understand the value of ToString/Message now. I put that back in my latest commit. You can see how it will work in these tests:

> Even custom renderers are a pain in this SDK, because Async always returns AggregateExceptions that need to be unwrapped. So each place you have an exception, you need to check to see if its an AggregateException, unwrap it

Just double-checking: are you using async/await? `await` should be automatically unwrapping the AggregateException. Having to do it manually might be an antipattern. Your other points about logging details by default make sense. 👍

**Comment by ryannewington** [comment]
@nbarbettini that looks good!

I'm writing a connector for MIM (https://github.com/lithnet/okta-managementagent). It's basically a DLL that implements specific interfaces that MIM calls. It sits in between Okta and MIM and shuffles objects back and forward using those interfaces. If a particular object has an error, I need to catch that exception and turn it into an error record object to pass back to MIM. If I let the exception bubble up, it stops the whole import or export process. MIM is pre-async tech. The interfaces don't return Task objects.

**Comment by nbarbettini** [comment]
@laura-rodriguez Can you review this when you have a chance? Thank you!

**Pull request merged**
