### PR TITLE
Tests external contributions

### PR DESCRIPTION
**Pull request by vijetm**

### CODE REVIEW

**Comment by nbarbettini** [comment]
Looks like it still tried to run ITs. But it wasn't targeted to `vm-travis`, that's probably why?

**Comment by vijetm** [comment]
Yes. It'll start working after we merge this PR.

**Comment by laura-rodriguez** [comment]
@vijetm Can you test by pushing something with your personal account into the `vm-travis` branch? We should be able to test this before merging into master.

**Comment by vijetm** [comment]
Sure. Will do that

**Pull request closed without merging**
