### PR TITLE
:bug: Fixes an issue with creating users with a specific provider

### PR DESCRIPTION
**Pull request by ryannewington**
Fixes issue #187 where the CreateUserAsync overload that takes a CreateUserWithProviderOptions does not pass through the optional provider=true parameter to the underlying CreateUserAsync method

### CODE REVIEW

**Comment by nbarbettini** [comment]
Thanks for catching this! You'll need to update this branch (the big button above), then feel free to merge. If git doesn't cooperate, let me know.

**Comment by ryannewington** [comment]
I could update the branch, but I'm not allowed to merge

**Comment by nbarbettini** [comment]
Done!

**Comment by ryannewington** [comment]
Awesome. PS I only found this bug because I had #184 enabled and saw it in fiddler :)

**Comment by nbarbettini** [comment]
@ryannewington Are you able to use Fiddler's HTTPS decryption option? Or do you not want to trust their root cert?

**Comment by ryannewington** [comment]
It's a matter of trusting their root cert system-wide versus just for a single application. The MIM system usually has high level access to lots of different systems for provisioning purposes, and security is a concern. For helping customers troubleshoot, being able to set a 'debug' flag and have them send me outputs from fiddler traces is very valuable.

Alternatively, is there a way to log raw request/response data with the SDK? This would avoid having to do any certificate trickery at all.

**Pull request merged**
