### PR TITLE
519 Multi-Target .NET 5 and .NET 6

### PR DESCRIPTION
**Pull request by Christian-Oleson**
## Issue \#
#519 - Add Multi-targeting of the .NET SDK for .NET 5 and .NET 6

## Code

- [ ] Unit test(s)
- [ ] Implementation

## Current behavior
N/a

## Desired behavior
N/a

## Additional Context
The Travis CI builds will fail until .NET 6 is added to the dependencies. I'm not sure where to add that.

### CODE REVIEW

**Comment by monde** [comment]
Ack, this is a sibling to #519 519

**Comment by Christian-Oleson** [comment]
> Ack, this is a sibling to #519 519

Just checking on this one?

**Comment by andriizhegurov-okta** [comment]
Hi @Christian-Oleson, thanks for the contribution. We have this in our roadmap. 
Currently our team is busy with other tasks, but we'll get back to this as soon as possible.

**Comment by Christian-Oleson** [comment]
> Hi @Christian-Oleson, thanks for the contribution. We have this in our roadmap. Currently our team is busy with other tasks, but we'll get back to this as soon as possible.

Is there any update on this?

**Comment by Christian-Oleson** [comment]
Closing, as I'm tired of this PR sitting and waiting

**Pull request closed without merging**
