### PR TITLE
:seedling: Adds support for skinny_users endpoint, error causes in OktaApiException, support for API rate-limiting and disabling certificate validation for debugging purposes

### PR DESCRIPTION
**Pull request by ryannewington**
Adds support for calling the skinny_users endpoint to get a smaller representation of the users who are a member of a group as documented in the following guide https://www.okta.com/sites/default/files/Okta_Security-Analytics_Partner-Integration-Guide.pdf

### CODE REVIEW

**Comment by nbarbettini** [comment]
Hey @ryannewington, thanks for the contributions! I'll take a look at these soon.

**Comment by nbarbettini** [comment]
Quick question - do you mind moving the OktaApiException stuff into a separate PR? That should be a quick-'n-easy merge. I need to check the other stuff against the roadmap.

I can do the PR splitting if it's a pain. 😄

**Comment by ryannewington** [comment]
Hey @nbarbettini. Nice to meet a fellow MVP out in the wilds!

I did plan on sending on PR per feature, but after I made the first one, the subsequent commits automatically added themselves to the first PR :| I'll confess that I'm not a git expert.

I'll have another go and splitting them out. I might have to delete this one and start again.

**Comment by ryannewington** [comment]
Have split them all into seperate PRs. 

(RIP my repo 😢)

**Comment by nbarbettini** [comment]
Great to meet you too @ryannewington! 👋 

No worries, it took me a while to get used to Git. I'm happy to help if you get stuck again.

**Pull request closed without merging**
